index:
   path: /
   controller: App\Controller\IndexController::index

register:
   path: /inscription/{links}
   controller: App\Controller\SecurityController::register
   requirements:
      link: "[.]*"

login:
   path: /connexion
   controller: App\Controller\SecurityController::login

logout:
   path: /deconnexion
   controller: App\Controller\SecurityController::logout

profil:
   path: /profil
   controller: App\Controller\ProfilController::perso

profilEdit:
   path: /profil/modification
   controller: App\Controller\ProfilController::edit

vips:
   path: /vips
   controller: App\Controller\VipsController::list

addModo:
   path: /modo/ajout
   controller: App\Controller\ModoController::add

modo:
   path: /modo
   controller: App\Controller\ModoController::list

suppress:
   path: /suppress
   controller: App\Controller\SuppressController::suppress